
  arrS = [
    "JavaScript",
    "Python",
    "Java",
    "HTML",
    "CSS",
    "React",
    "Node.js",
    "Angular",
    "Vue.js",
    "TypeScript",
    "PHP",
    "Ruby",
    "C++",
    "C#",
    "Swift",
    "Android Development",
    "iOS Development",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Firebase",
    "Django",
    "Flask",
    "Express.js",
    "Spring Boot",
    "ASP.NET",
    "RESTful API",
    "GraphQL",
    "JSON",
    "XML",
    "WebSockets",
    "Bootstrap",
    "Materialize",
    "Sass",
    "LESS",
    "D3.js",
    "Redux",
    "Vuex",
    "JQuery",
    "Webpack",
    "NPM",
    "Yarn",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Travis CI",
    "Heroku",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Linux",
    "Shell Scripting",
    "Bash",
    "PowerShell",
    "Agile",
    "Scrum",
    "Kanban",
    "JIRA",
    "Confluence",
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Test-Driven Development (TDD)",
    "Continuous Integration (CI)",
    "Responsive Design",
    "Cross-browser Compatibility",
    "Accessibility",
    "SEO Optimization",
    "Performance Optimization",
    "User Experience (UX) Design",
    "User Interface (UI) Design",
    "Wireframing",
    "Prototyping",
    "Adobe XD",
    "Figma",
    "Sketch",
    "Photoshop",
    "Illustrator",
    "InDesign",
    "3D Modeling",
    "Unity",
    "Blender",
    "AR/VR Development",
    "Machine Learning",
    "Artificial Intelligence",
    "Data Science",
    "Big Data",
    "Blockchain",
    "Cybersecurity",
    "Penetration Testing",
    "Ethical Hacking",
    "Network Administration",
    "DevOps",
    "Microservices Architecture",
    "Serverless Computing",
    "IoT Development",
    "Robotics",
    "Natural Language Processing (NLP)",
    "Chatbot Development",
    "Video Editing",
    "Audio Production",
    "Game Development",
    "Virtual Reality (VR)",
    "Augmented Reality (AR)",
    "Sales",
    "Marketing",
    "Customer Relationship Management (CRM)",
    "Negotiation",
    "Presentation Skills",
    "Market Research",
    "Lead Generation",
    "Closing Skills",
    "Time Management",
    "Adaptability",
    "Active Listening",
    "Problem Solving",
    "Critical Thinking",
    "Decision Making",
    "Teamwork",
    "Leadership",
    "Emotional Intelligence",
    "Conflict Resolution",
    "Effective Communication",
    "Public Speaking",
    "Networking",
    "Written Communication",
    "Interpersonal Skills",
    "Time Management",
    "Organizational Skills",
    "Problem Solving",
    "Adaptability",
    "Decision Making",
    "Creative Thinking",
    "Stress Management",
    "Emotional Intelligence",
    "Teamwork",
    "Leadership",
    "Conflict Resolution",
    "Active Listening",
    "Crisis Management",
    "Cross-cultural Competence",
    "Feedback",
    "Collaboration",
    "Innovation",
    "Influence",
    "Motivation",
    "Persuasion",
    "Resilience",
    "Self-motivation",
    "Strategic Thinking",
    "Analytical Thinking",
    "Attention to Detail",
    "Continuous Learning",
    "Curiosity",
    "Flexibility",
    "Resourcefulness",
    "Time Management",
    "Multitasking",
    "Prioritization",
    "Goal Setting",
    "Decision Making",
    "Networking",
    "Adaptability",
    "Teamwork",
    "Leadership",
    "Delegation",
    "Project Management",
    "Budgeting",
    "Financial Literacy",
    "Contract Negotiation",
    "Business Development",
    "Conflict Resolution",
    "Critical Thinking",
    "Problem Solving",
    "Innovation",
    "Strategic Planning",
    "Risk Management",
    "Change Management",
    "Quality Management",
    "Vendor Management",
    "Supply Chain Management",
    "Negotiation",
    "Conflict Resolution",
    "Active Listening",
    "Presentation Skills",
    "Public Speaking",
    "Written Communication",
    "Interpersonal Skills",
    "Time Management",
    "Organizational Skills",
    "Problem Solving",
    "Adaptability",
    "Decision Making",
    "Creative Thinking",
    "Stress Management",
    "Emotional Intelligence",
    "Teamwork",
    "Leadership",
    "Conflict Resolution",
    "Active Listening",
    "Crisis Management",
    "Cross-cultural Competence",
    "Feedback",
    "Collaboration",
    "Innovation",
    "Influence",
    "Motivation",
    "Persuasion",
    "Resilience",
    "Self-motivation",
    "Strategic Thinking",
    "Analytical Thinking",
    "Attention to Detail",
    "Continuous Learning",
    "Curiosity",
    "Flexibility",
    "Resourcefulness",
    "Time Management",
    "Multitasking",
    "Prioritization",
    "Goal Setting",
    "Decision Making",
    "Networking",
    "Adaptability",
    "Teamwork",
    "Leadership",
    "Delegation",
    "Project Management",
    "Budgeting",
    "Financial Literacy",
    "Contract Negotiation",
    "Business Development",
    "Conflict Resolution",
    "Critical Thinking",
    "Problem Solving",
    "Innovation",
    "Strategic Planning",
    "Risk Management",
    "Change Management",
    "Quality Management",
    "Vendor Management",
    "Supply Chain Management",
    "Negotiation",
    "Conflict Resolution",
    "Active Listening",
    "Presentation Skills",
    "Public Speaking",
    "Written Communication",
    "Interpersonal Skills",
    "Time Management",
    "Organizational Skills",
    "Problem Solving",
    "Adaptability",
    "Decision Making",
    "Creative Thinking",
    "Stress Management",
    "Emotional Intelligence",
    "Teamwork",
    "Leadership",
    "Conflict Resolution",
    "Active Listening",
    "Crisis Management",
    "Cross-cultural Competence",
    "Feedback",
    "Collaboration",
    "Innovation",
    "Influence",
    "Motivation",
    "Persuasion",
    "Resilience",
    "Self-motivation",
    "Strategic Thinking",
    "Analytical Thinking",
    "Attention to Detail",
    "Continuous Learning",
    "Curiosity",
    "Flexibility",
    "Resourcefulness",
    "Time Management",
    "Multitasking",
    "Prioritization",
    "Goal Setting",
    "Decision Making",
    "Networking",
    "Adaptability",
    "Teamwork",
    "Leadership",
    "Delegation",
    "Project Management",
    "Budgeting",
    "Financial Literacy",
    "Contract Negotiation",
    "Business Development",
    "Conflict Resolution",
    "Critical Thinking",
    "Problem Solving",
    "Innovation",
    "Strategic Planning",
    "Risk Management",
    "Change Management",
    "Quality Management",
    "Vendor Management",
    "Supply Chain Management",
    "Negotiation",
    "Conflict Resolution",
    "Active Listening",
    "Presentation Skills",
    "Public Speaking",
    "Written Communication",
    "Interpersonal Skills",
    "Time Management",
    "Organizational Skills",
    "Problem Solving",
    "Adaptability",
    "Decision Making",
    "Creative Thinking",
    "Stress Management",
    "Emotional Intelligence",
    "Teamwork",
    "Leadership",
    "Conflict Resolution",
    "Active Listening",
    "Crisis Management",
    "Cross-cultural Competence",
    "Feedback",
    "Collaboration",
    "Innovation",
    "Influence",
    "Motivation",
    "Persuasion",
    "Resilience",
    "Self-motivation",
    "Strategic Thinking",
    "Analytical Thinking",
    "Attention to Detail",
    "Continuous Learning",
    "Curiosity",
    "Flexibility",
    "Resourcefulness",
    "Time Management",
    "Multitasking",
    "Prioritization",
    "Goal Setting",
    "Decision Making",
    "Networking",
    "Adaptability",
    "Teamwork",
    "Leadership",
    "Delegation",
    "Project Management",
    "Budgeting",
    "Financial Literacy",
    "Contract Negotiation",
    "Business Development",
    "Conflict Resolution",
    "Critical Thinking",
    "Problem Solving",
    "Innovation",
    "Strategic Planning",
    "Risk Management",
    "Change Management",
    "Quality Management",
    "Vendor Management",
    "Supply Chain Management",
    "Negotiation",
    "Conflict Resolution",
    "Active Listening",
    "Presentation Skills",
    "Public Speaking",
    "Written Communication",
    "Interpersonal Skills",
    "Time Management",
    "Organizational Skills",
    "Problem Solving",
    "Adaptability",
    "Decision Making",
    "Creative Thinking",
    "Stress Management",
    "Emotional Intelligence",
    "Teamwork",
    "Leadership",
    "Conflict Resolution",
    "Active Listening",
    "Crisis Management",
    "Cross-cultural Competence",
    "Feedback",
    "Collaboration",
    "Innovation",
    "Influence",
    "Motivation",
    "Persuasion",
    "Resilience",
    "Self-motivation",
    "Strategic Thinking",
    "Analytical Thinking",
    "Attention to Detail",
    "Continuous Learning",
    "Curiosity",
    "Flexibility",
    "Resourcefulness",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Linux",
    "Shell Scripting",
    "Bash",
    "PowerShell",
    "Agile",
    "Scrum",
    "Kanban",
    "JIRA",
    "Confluence",
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Test-Driven Development (TDD)",
    "Continuous Integration (CI)",
    "Responsive Design",
    "Cross-browser Compatibility",
    "Accessibility",
    "SEO Optimization",
    "Performance Optimization",
    "User Experience (UX) Design",
    "User Interface (UI) Design",
    "Wireframing",
    "Prototyping",
    "Adobe XD",
    "Figma",
    "Sketch",
    "Photoshop",
    "Illustrator",
    "InDesign",
    "3D Modeling",
    "Unity",
    "Blender",
    "AR/VR Development",
    "Machine Learning",
    "Artificial Intelligence",
    "Data Science",
    "Big Data",
    "Blockchain",
    "Cybersecurity",
    "Penetration Testing",
    "Ethical Hacking",
    "Network Administration",
    "DevOps",
    "Microservices Architecture",
    "Serverless Computing",
    "IoT Development",
    "Robotics",
    "Natural Language Processing (NLP)",
    "Chatbot Development",
    "Video Editing",
    "Audio Production",
    "Game Development",
    "Virtual Reality (VR)",
    "Augmented Reality (AR)",
    "Sales",
    "Marketing",
    "Customer Relationship Management (CRM)",
    "Negotiation",
    "Presentation Skills",
    "Market Research",
    "Lead Generation",
    "Closing Skills",
    "Time Management",
    "Adaptability",
    "Active Listening",
    "Problem Solving",
    "Critical Thinking",
    "Decision Making",
    "Teamwork",
    "Leadership",
    "Emotional Intelligence",
    "Conflict Resolution",
    "Effective Communication",
    "Public Speaking",
    "Networking",
    "Written Communication",
    "Interpersonal Skills",
    "Time Management",
    "Organizational Skills",
    "Problem Solving",
    "Adaptability",
    "Decision Making",
    "Creative Thinking",
    "Stress Management",
    "Emotional Intelligence",
    "Teamwork",
    "Leadership",
    "Conflict Resolution",
    "Active Listening",
    "Crisis Management",
    "Cross-cultural Competence",
    "Feedback",
    "Collaboration",
    "Innovation",
    "Influence",
    "Motivation",
    "Persuasion",
    "Resilience",
    "Self-motivation",
    "Strategic Thinking",
    "Analytical Thinking",
    "Attention to Detail",
    "Continuous Learning",
    "Curiosity",
    "Flexibility",
    "Resourcefulness",
    "Time Management",
    "Multitasking",
    "Prioritization",
    "Goal Setting",
    "Decision Making",
    "Networking",
    "Adaptability",
    "Teamwork",
    "Leadership",
    "Delegation",
    "Project Management",
    "Budgeting",
    "Financial Literacy",
    "Contract Negotiation",
    "Business Development",
    "Conflict Resolution",
    "Critical Thinking",
    "Problem Solving",
    "Innovation",
    "Strategic Planning",
    "Risk Management",
    "Change Management",
    "Quality Management",
    "Vendor Management",
    "Supply Chain Management",
    "Negotiation",
    "Conflict Resolution",
    "Active Listening",
    "Presentation Skills",
    "Public Speaking",
    "Written Communication",
    "Interpersonal Skills",
    "Time Management",
    "Organizational Skills",
    "Problem Solving",
    "Adaptability",
    "Decision Making",
    "Creative Thinking",
    "Stress Management",
    "Emotional Intelligence",
    "Teamwork",
    "Leadership",
    "Conflict Resolution",
    "Active Listening",
    "Crisis Management",
    "Cross-cultural Competence",
    "Feedback",
    "Collaboration",
    "Innovation",
    "Influence",
    "Motivation",
    "Persuasion",
    "Resilience",
    "Self-motivation",
    "Strategic Thinking",
    "Analytical Thinking",
    "Attention to Detail",
    "Continuous Learning",
    "Curiosity",
    "Flexibility",
    "Resourcefulness",
    "Time Management",
    "Multitasking",
    "Prioritization",
    "Goal Setting",
    "Decision Making",
    "Networking",
    "Adaptability",
    "Teamwork",
    "Leadership",
    "Delegation",
    "Project Management",
    "Budgeting",
    "Financial Literacy",
    "Contract Negotiation",
    "Business Development",
    "Conflict Resolution",
    "Critical Thinking",
    "Problem Solving",
    "Innovation",
    "Strategic Planning",
    "Risk Management",
    "Change Management",
    "Quality Management",
    "Vendor Management",
    "Supply Chain Management",
    "Negotiation",
    "Conflict Resolution",
    "Active Listening",
    "Presentation Skills",
    "Public Speaking",
    "Written Communication",
    "Interpersonal Skills",
    "Time Management",
    "Organizational Skills",
    "Problem Solving",
    "Adaptability",
    "Decision Making",
    "Creative Thinking",
    "Stress Management",
    "Emotional Intelligence",
    "Teamwork",
    "Leadership",
    "Conflict Resolution",
    "Active Listening",
    "Crisis Management",
    "Cross-cultural Competence",
    "Feedback",
    "Collaboration",
    "Innovation",
    "Influence",
    "Motivation",
    "Persuasion",
    "Resilience",
    "Self-motivation",
    "Strategic Thinking",
    "Analytical Thinking",
    "Attention to Detail",
    "Continuous Learning",
    "Curiosity",
    "Flexibility",
    "Resourcefulness",
    "Time Management",
    "Multitasking",
    "Prioritization",
    "Goal Setting",
    "Decision Making",
    "Networking",
    "Adaptability",
    "Teamwork",
    "Leadership",
    "Delegation",
    "Project Management",
    "Budgeting",
    "Financial Literacy",
    "Contract Negotiation",
    "Business Development",
    "Conflict Resolution",
    "Critical Thinking",
    "Problem Solving",
    "Innovation",
    "Strategic Planning",
    "Risk Management",
    "Change Management",
    "Quality Management",
    "Vendor Management",
    "Supply Chain Management",
    "Negotiation",
    "Conflict Resolution",
    "Active Listening",
    "Presentation Skills",
    "Public Speaking",
    "Written Communication",
    "Interpersonal Skills",
    "Time Management",
    "Organizational Skills",
    "Problem Solving",
    "Adaptability",
    "Decision Making",
    "Creative Thinking",
    "Stress Management",
    "Emotional Intelligence",
    "Teamwork",
    "Leadership",
    "Conflict Resolution",
    "Active Listening",
    "Crisis Management",
    "Cross-cultural Competence",
    "Feedback",
    "Collaboration",
    "Innovation",
    "Influence",
    "Motivation",
    "Persuasion",
    "Resilience",
    "Self-motivation",
    "Strategic Thinking",
    "Analytical Thinking",
    "Attention to Detail",
    "Continuous Learning",
    "Curiosity",
    "Flexibility",
    "Resourcefulness",
    "Time Management",
    "Multitasking",
    "Prioritization",
    "Goal Setting",
    "Decision Making",
    "Networking",
    "Adaptability",
    "Teamwork",
    "Leadership",
    "Delegation",
    "Project Management",
    "Budgeting",
    "Financial Literacy",
    "Contract Negotiation",
    "Business Development",
    "Conflict Resolution",
    "Critical Thinking",
    "Problem Solving",
    "Innovation",
    "Strategic Planning",
    "Risk Management",
    "Change Management",
    "Quality Management",
    "Vendor Management",
    "Supply Chain Management",
    "Negotiation",
    "Conflict Resolution",
    "Active Listening",
    "Presentation Skills",
    "Public Speaking",
    "Written Communication",
    "Interpersonal Skills",
    "Time Management",
    "Organizational Skills",
    "Problem Solving",
    "Adaptability",
    "Decision Making",
    "Creative Thinking",
    "Stress Management",
    "Emotional Intelligence",
    "Teamwork",
    "Leadership",
    "Conflict Resolution",
    "Active Listening",
    "Crisis Management",
    "Cross-cultural Competence",
    "Feedback",
    "Collaboration",
    "Innovation",
    "Influence",
    "Motivation",
    "Persuasion",
    "Resilience",
    "Self-motivation",
    "Strategic Thinking",
    "Analytical Thinking",
    "Attention to Detail",
    "Continuous Learning",
    "Curiosity",
    "Flexibility",
    "Resourcefulness"
  ]


export default arrS;